language: bash

script:
  - shellcheck *.sh
  - shellcheck functions/*.sh
  - shellcheck tools/*.sh

sudo: required

addons:
  apt:
    packages:
      - git

after_success: |
  sudo bash deploy.sh dryrun
