language: bash

sudo: required

addons:
  apt:
    packages:
      - git

after_success: |
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/bilyboy785/site-deployer/master/tools/install.sh)"
  deploy dryrun martinbouillaud bouillaudmartin.fr dev.bouillaudmartin.fr